### ISSUE TITLE
The link to tutorial is wrong

### ISSUE THREAD

**Issue by gnaghi** [breakin/snestistics-homepage-staging#1]
Link https://breakin.github.io/snestistics/tutorial-1 on https://breakin.github.io/snestistics/user-guide is wrong (should be https://breakin.github.io/snestistics/tutorial).

**Comment by breakin** [comment]
Thanks! Fixed!
Also added a note about how I want to work with snestistics at the starting page (see text block under "Current Limitations"). I'd love to learn more about how snestistics works out for you, but I guess I will be following you by reading all issues you post :) Feel free to post feature requests!
